### ISSUE TITLE
Lack of clear setup description

### ISSUE THREAD

**Issue by opaugam** [mesos/cloudfoundry-mesos#7]
Hey - i've been trying to setup this project as part of an evaluation spike but have to admit am getting nowhere. Would it be possible to have a clear description of how this was tested ? The executor does not seem to start for me and dies after a bit, the auctioneer code appears to be stale and so on. Is this project still active ?

**Comment by jianhuiz** [comment]
the executor is basically a Diego cell, you could find the logs of each cell jobs under "var/vcap/sys/log" of the container sandbox. It is likely because of the different configuration between your CF deployment and the image.

**Comment by deepak-vij** [comment]
As mentioned in the documentation that this is a very initial version of the framework and is a work-in-progress. We are expecting community as a whole to collaborate and evolve it as we go along. It is by no means production ready at this time. Thanks.
-   Deepak

**Comment by opaugam** [comment]
um, i'm not expecting something production ready, i was wondering about maybe describing precisely how you get set the whole thing up on your end..

**Comment by deepak-vij** [comment]
The description is quite self explanatory. Although, we would be very happy to help out if you can precisely mention what is not clear in the documentation..
